### ISSUE TITLE
[WIP] Release 4.0.0

### ISSUE THREAD

**Issue by Jarthianur** [Jarthianur/VFR-Backend#67]
This issue tracks the release status for version 4.

TODO:

- [x] Fix all existing tests
- [x] Change all processors to use libfmt instead of old C functions
- [ ] Verify this to be working for moving station - in flight
- [ ] Verify new concurrent container to be threadsafe
- [ ] Verify new concurrent access to aircrafts does not break round based processing logic
- [ ] Verify in-place and pointer based string processing to be safe
- [ ] Audit code
  - [ ] Double check everything to be safe and secure
  - [ ] Rename and refactor where necessary
  - [ ] Check code style consistency
  - [ ] Write code-docs
- [ ] Rewrite docs and readme to be up-to-date and more clear and concise
- [ ] Update versions and changelogs
